[project]
name = "LOVEBrew"
description = "A web application to build your LOVE Potion projects"
requires-python = ">=3.8"
dependencies = [
    "flask",
    "flask-cors",
    "waitress",
    "pyopenssl",
    "requests",
    "filetype",
    "semver",
    "hurry.filesize",
    "toml",
]
version = "0.8.0"

[tool.setuptools.package-data]
"lovebrew.static" = ["**"]

[project.urls]
Donate = "https://paypal.me/TurtleP"
"Source Code" = "https://github.com/lovebrew/lovebrew-webserver/"
"Issue Tracker" = "https://github.com/lovebrew/lovebrew-webserver/issues/"
